name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Test
        run: go test ./...

      - name: Build
        run: |
          go build \
            -ldflags "-X main.repoURL=https://github.com/hirrrooo/mc-backup.git -X main.version=${{ github.ref_name }}" \
            -o mc-backup-linux-amd64 \
            ./cmd/mc-backup

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: mc-backup-linux-amd64
